/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Bukti_pendukungRouteImport } from './routes/bukti_pendukung'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PengaduanRouteImport } from './routes/pengaduan'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as SurveiRouteImport } from './routes/survei'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Bukti_pendukungRoute = Bukti_pendukungRouteImport.update({
  id: '/bukti_pendukung',
  path: '/bukti_pendukung',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaduanRoute = PengaduanRouteImport.update({
  id: '/pengaduan',
  path: '/pengaduan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveiRoute = SurveiRouteImport.update({
  id: '/survei',
  path: '/survei',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bukti_pendukung': typeof Bukti_pendukungRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pengaduan': typeof PengaduanRoute
  '/setting': typeof SettingRoute
  '/survei': typeof SurveiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bukti_pendukung': typeof Bukti_pendukungRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pengaduan': typeof PengaduanRoute
  '/setting': typeof SettingRoute
  '/survei': typeof SurveiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bukti_pendukung': typeof Bukti_pendukungRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pengaduan': typeof PengaduanRoute
  '/setting': typeof SettingRoute
  '/survei': typeof SurveiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bukti_pendukung'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/pengaduan'
    | '/setting'
    | '/survei'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bukti_pendukung'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/pengaduan'
    | '/setting'
    | '/survei'
  id:
    | '__root__'
    | '/'
    | '/bukti_pendukung'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/pengaduan'
    | '/setting'
    | '/survei'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Bukti_pendukungRoute: typeof Bukti_pendukungRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PengaduanRoute: typeof PengaduanRoute
  SettingRoute: typeof SettingRoute
  SurveiRoute: typeof SurveiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bukti_pendukung': {
      id: '/bukti_pendukung'
      path: '/bukti_pendukung'
      fullPath: '/bukti_pendukung'
      preLoaderRoute: typeof Bukti_pendukungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaduan': {
      id: '/pengaduan'
      path: '/pengaduan'
      fullPath: '/pengaduan'
      preLoaderRoute: typeof PengaduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survei': {
      id: '/survei'
      path: '/survei'
      fullPath: '/survei'
      preLoaderRoute: typeof SurveiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Bukti_pendukungRoute: Bukti_pendukungRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PengaduanRoute: PengaduanRoute,
  SettingRoute: SettingRoute,
  SurveiRoute: SurveiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
